# Generated by Django 5.0.4 on 2024-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateField(verbose_name='Reading date'),
        ),
    ]
