# Generated by Django 5.0.4 on 2024-04-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_translator_alter_reading_options_alter_reading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(to='main_app.translator'),
        ),
    ]
